### ISSUE TITLE
Materials are out-of-sync with the template

### ISSUE THREAD

**Issue by ooharawork** [corda/corda-training-materials#3]
As you probably know, the materials are now out-of-sync with recent updates on the template (`corda-training-template`).
Newer pdfs, that are possibly used in the current course, if any, should be reflected to this repository, for consistency.

Example of updates to be reflected: 
In `Module 10 - Plugins and APIs.pdf`:

- page 14 says we will get `404` error
    - -> the actual code already has a respective receptacle and we won't get `404` (for this, I created a separate issue:  corda/corda-training-template#20 )
- page 23 says we return `Accepted` response
    - -> Instead, we should return `Created`
- page 34 says we should call `services.startFlowDynamic(IOUIssueFlow::class.java, state, lender)`
    - -> `rpcOps.startTrackedFlow(::IOUIssueFlow, state)` would be appropriate

**Comment by bennytanr3** [comment]
The value of teaching Restful APIs in Jetty has diminished when we consider the deprecation of the webserver in favour of an external package e.g. springboot. In springboot, the implementation for the API would have been different. Good catch nonetheless.

page 14: suggests commenting out in the corda-training-template, GET 'ious'
page 23: Will update the deck to `Created`
page 34:  Will update the deck to   `rpcOps.startTrackedFlow(::IOUIssueFlow,` state)`

**Comment by ooharawork** [comment]
Thanks for the comment and the amendments. Got that Jetty-based materials will be obsoleted and we should rather move on to springboot etc. 
This might be a little bit picky, but `IOUIssueFlow::` should be typo of `::IOUIssueFlow` in #5  .

**Comment by bennytanr3** [comment]
Sorry about this, I have updated the deck again.

**Comment by ooharawork** [comment]
Thanks again! confirmed.
